FROM ubuntu:20.04

ENV BUILD_DIR="build"
ENV APPLICATION_BINARY="Application"
ENV OPEN_PORT=8080

WORKDIR /app
COPY ${BUILD_DIR}/${APPLICATION_BINARY} .

EXPOSE ${OPEN_PORT}
CMD [ "./${APPLICATION_BINARY}" ]